[package]
name = "DAOShip"
version = "1.0.0"
authors = ["DAOShip Team"]

[addresses]
daoship = "0x42"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
